### ISSUE TITLE
Point to the documentation instead of listing build init types

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-applications#1]
Instead of listing build init types available today, we can point to the documentation at https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:build_init_types.

This is what we do in https://gradle.org/getting-started/creating-a-build.

This should make the guide easier to maintain.

**Comment by ysb33r** [comment]
Let's discuss this in the team meeting (would have been nice if we had a `needs:discussion` label).

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #216](https://github.com/gradle/guides/issues/216) via [**ZenHub**](https://www.zenhub.com/)
