### ISSUE TITLE
Build tree creates a "libs" folder instead of "lib" folder

### ISSUE THREAD

**Issue by lotsoaxolotls** [gradle-guides/building-java-applications#10]
While trying out the Gradle example documented at https://guides.gradle.org/building-java-applications/, I encountered an issue when trying to run the test.bat script: Error: Could not find or load main class App.

After some investigation, it turns out the batch script has the build\lib directory in its classpath when invoking java, but the actual build tree has a folder called build\libs, not build\lib.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #242](https://github.com/gradle/guides/issues/242) via [**ZenHub**](https://www.zenhub.com/)
