### ISSUE TITLE
Typo in guides - Building Java Applications

### ISSUE THREAD

**Issue by sannidhi01** [gradle-guides/building-java-applications#14]
In [Building Java Applications](https://guides.gradle.org/building-java-applications/) guide, under [Review the generated project files](https://guides.gradle.org/building-java-applications/#review_the_generated_project_files) section, a statement reads as 'This assigns the name of the root project to java-demo...'. I think it should be 'demo', not 'java-demo'.

Note: I tried to update by myself but, couldn't find repo(for guides). Please point to it so that in future the process could be expedite.

**Comment by pledbrook** [comment]
This is the repo for the guide, as linked at the end of the guide under the section "Help improve this guide".

**Comment by sannidhi01** [comment]
Thanks for clarification and being kind(unlike other sites, wherein I would have been BLASTED). This is my first, ever, public activity here so, just want to make sure I play safe. 
As the issue seems to be resolved, I'm closing this.
