### ISSUE TITLE
gradle init --type java-application command does not ask for any values

### ISSUE THREAD

**Issue by garybentley** [gradle-guides/building-java-applications#16]
Using gradle 5.2.1 running the command:

> gradle init --type java-application

did not ask me any questions, it only produced the following result:

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed

The guide suggests that it should be asking me for some values but it's not.

**Comment by das-g** [comment]
This seems to depend on the Gradle version:
- Gradle 4.10.2 didn't ask me
  ```
  $ gradle init --type java-application
  Starting a Gradle Daemon (subsequent builds will be faster)
  > Task :wrapper
  > Task :init
  
  BUILD SUCCESSFUL in 2s
  2 actionable tasks: 2 executed
  ```
- Gradle 5.3.1 did ask me
  ```
  $ gradle init --type java-application
  > Task :wrapper
  
  Select build script DSL:
    1: groovy
    2: kotlin
  Enter selection (default: groovy) [1..2] 
  
  Select test framework:
    1: junit
    2: testng
    3: spock
  Enter selection (default: junit) [1..3] 
  
  Project name (default: demo): 
  
  Source package (default: demo): 
  
  > Task :init
  
  BUILD SUCCESSFUL in 11s
  2 actionable tasks: 2 executed
  ```

This confused me too, when following the guide with Gradle 4.10.2. (Especially since the guide doesn't mention what Gradle version it expects.)

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #270](https://github.com/gradle/guides/issues/270) via [**ZenHub**](https://www.zenhub.com/)
