### ISSUE TITLE
Rename the guide to "Building Java applications"

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-applications#2]
Let's use consistent terms in titles and settle on "building" vs "creating". The other similar guide about libraries is called [Building JVM libraries](https://guides.gradle.org/building-jvm-libraries/). I think "building" is better because that's the focus of the tool.

We can also rename to "Building Java **executable** applications" while we are on it to distinguish from "Building Java **web** applications" that we should cover in a separate guide (https://github.com/gradle/guides/issues/75).

**Comment by kousen** [comment]
I like the phrase "building" rather than "creating". I would not have thought of "executable", but since you contrast it with "web" it makes sense. I agree with both, as well as the web app guide idea.

**Comment by kousen** [comment]
Reassigned to @ysb33r because he can work with @chaficnajjar in a more friendly time zone :)

**Comment by ysb33r** [comment]
@chaficnajjar Here is one more ot the repositories that require renaming.

**Comment by ysb33r** [comment]
- [x] Rename repo on GH.
- [x] Update title.
- [x] Update `dotorg-site`.
- [x] CloudFlare redirect.
- [x] Update description on GH to reflect title & slug.
