### ISSUE TITLE
Build Guide Doesn't Help With No Src, or No Run Issues

### ISSUE THREAD

**Issue by Paula9t9** [gradle-guides/building-java-applications#21]
Following the [build guide](https://guides.gradle.org/building-java-applications/), I ran into three issues:

1. Gradle initialized with no src directory
2. build/reports/tests/test/index.html gave me a "Permission denied" error
3. run was not listed as an available task

While I am perfectly capable of googling solutions to these issues, it was still frustrating that the tutorial didn't acknowledge what to do in these situations.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #284](https://github.com/gradle/guides/issues/284) via [**ZenHub**](https://www.zenhub.com/)
