### ISSUE TITLE
Environment Management

### ISSUE THREAD

**Issue by jrlmx2** [gradle-guides/building-java-applications#8]
Typically there is a local, staging, and production build process. This is usually handled through  build command line params.

I usually handle this in projects through a task + doFirst, for example 

local{
    doFirst {
          classX.ext.env = "production"
     }
}

OR

gradle -Penvironment=production 

Link to something like this through the documentation, or include a snippet of how one would manage that as a suggestion?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #244](https://github.com/gradle/guides/issues/244) via [**ZenHub**](https://www.zenhub.com/)
